// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetDocumentsIDOKCode is the HTTP code returned for type GetDocumentsIDOK
const GetDocumentsIDOKCode int = 200

/*
GetDocumentsIDOK Document details

swagger:response getDocumentsIdOK
*/
type GetDocumentsIDOK struct {
}

// NewGetDocumentsIDOK creates GetDocumentsIDOK with default headers values
func NewGetDocumentsIDOK() *GetDocumentsIDOK {

	return &GetDocumentsIDOK{}
}

// WriteResponse to the client
func (o *GetDocumentsIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// GetDocumentsIDUnauthorizedCode is the HTTP code returned for type GetDocumentsIDUnauthorized
const GetDocumentsIDUnauthorizedCode int = 401

/*
GetDocumentsIDUnauthorized Unauthorized

swagger:response getDocumentsIdUnauthorized
*/
type GetDocumentsIDUnauthorized struct {
}

// NewGetDocumentsIDUnauthorized creates GetDocumentsIDUnauthorized with default headers values
func NewGetDocumentsIDUnauthorized() *GetDocumentsIDUnauthorized {

	return &GetDocumentsIDUnauthorized{}
}

// WriteResponse to the client
func (o *GetDocumentsIDUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// GetDocumentsIDNotFoundCode is the HTTP code returned for type GetDocumentsIDNotFound
const GetDocumentsIDNotFoundCode int = 404

/*
GetDocumentsIDNotFound Not found

swagger:response getDocumentsIdNotFound
*/
type GetDocumentsIDNotFound struct {
}

// NewGetDocumentsIDNotFound creates GetDocumentsIDNotFound with default headers values
func NewGetDocumentsIDNotFound() *GetDocumentsIDNotFound {

	return &GetDocumentsIDNotFound{}
}

// WriteResponse to the client
func (o *GetDocumentsIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
