// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetUsersProfileHandlerFunc turns a function with the right signature into a get users profile handler
type GetUsersProfileHandlerFunc func(GetUsersProfileParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetUsersProfileHandlerFunc) Handle(params GetUsersProfileParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetUsersProfileHandler interface for that can handle valid get users profile params
type GetUsersProfileHandler interface {
	Handle(GetUsersProfileParams, interface{}) middleware.Responder
}

// NewGetUsersProfile creates a new http.Handler for the get users profile operation
func NewGetUsersProfile(ctx *middleware.Context, handler GetUsersProfileHandler) *GetUsersProfile {
	return &GetUsersProfile{Context: ctx, Handler: handler}
}

/*
	GetUsersProfile swagger:route GET /users/profile getUsersProfile

Get current user profile
*/
type GetUsersProfile struct {
	Context *middleware.Context
	Handler GetUsersProfileHandler
}

func (o *GetUsersProfile) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetUsersProfileParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
