// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetUsersProfileOKCode is the HTTP code returned for type GetUsersProfileOK
const GetUsersProfileOKCode int = 200

/*
GetUsersProfileOK OK

swagger:response getUsersProfileOK
*/
type GetUsersProfileOK struct {
}

// NewGetUsersProfileOK creates GetUsersProfileOK with default headers values
func NewGetUsersProfileOK() *GetUsersProfileOK {

	return &GetUsersProfileOK{}
}

// WriteResponse to the client
func (o *GetUsersProfileOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// GetUsersProfileUnauthorizedCode is the HTTP code returned for type GetUsersProfileUnauthorized
const GetUsersProfileUnauthorizedCode int = 401

/*
GetUsersProfileUnauthorized Unauthorized

swagger:response getUsersProfileUnauthorized
*/
type GetUsersProfileUnauthorized struct {
}

// NewGetUsersProfileUnauthorized creates GetUsersProfileUnauthorized with default headers values
func NewGetUsersProfileUnauthorized() *GetUsersProfileUnauthorized {

	return &GetUsersProfileUnauthorized{}
}

// WriteResponse to the client
func (o *GetUsersProfileUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
