// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewGetDocumentsParams creates a new GetDocumentsParams object
//
// There are no default values defined in the spec.
func NewGetDocumentsParams() GetDocumentsParams {

	return GetDocumentsParams{}
}

// GetDocumentsParams contains all the bound params for the get documents operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetDocuments
type GetDocumentsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Maximum number of documents to return
	  In: query
	*/
	Limit *int64

	/*Number of documents to skip
	  In: query
	*/
	Offset *int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetDocumentsParams() beforehand.
func (o *GetDocumentsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if rawLimit := r.URL.Query().Get("limit"); rawLimit != "" {
		value, err := strconv.ParseInt(rawLimit, 10, 64)
		if err != nil {
			res = append(res, errors.NewParseError("limit", "query", rawLimit, err))
		} else {
			o.Limit = &value
		}
	}

	if rawOffset := r.URL.Query().Get("offset"); rawOffset != "" {
		value, err := strconv.ParseInt(rawOffset, 10, 64)
		if err != nil {
			res = append(res, errors.NewParseError("offset", "query", rawOffset, err))
		} else {
			o.Offset = &value
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
