// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetDocumentsOKCode is the HTTP code returned for type GetDocumentsOK
const GetDocumentsOKCode int = 200

/*
GetDocumentsOK List of documents

swagger:response getDocumentsOK
*/
type GetDocumentsOK struct {
}

// NewGetDocumentsOK creates GetDocumentsOK with default headers values
func NewGetDocumentsOK() *GetDocumentsOK {

	return &GetDocumentsOK{}
}

// WriteResponse to the client
func (o *GetDocumentsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// GetDocumentsUnauthorizedCode is the HTTP code returned for type GetDocumentsUnauthorized
const GetDocumentsUnauthorizedCode int = 401

/*
GetDocumentsUnauthorized Unauthorized

swagger:response getDocumentsUnauthorized
*/
type GetDocumentsUnauthorized struct {
}

// NewGetDocumentsUnauthorized creates GetDocumentsUnauthorized with default headers values
func NewGetDocumentsUnauthorized() *GetDocumentsUnauthorized {

	return &GetDocumentsUnauthorized{}
}

// WriteResponse to the client
func (o *GetDocumentsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
