// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetDocumentsIDHandlerFunc turns a function with the right signature into a get documents ID handler
type GetDocumentsIDHandlerFunc func(GetDocumentsIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDocumentsIDHandlerFunc) Handle(params GetDocumentsIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetDocumentsIDHandler interface for that can handle valid get documents ID params
type GetDocumentsIDHandler interface {
	Handle(GetDocumentsIDParams, interface{}) middleware.Responder
}

// NewGetDocumentsID creates a new http.Handler for the get documents ID operation
func NewGetDocumentsID(ctx *middleware.Context, handler GetDocumentsIDHandler) *GetDocumentsID {
	return &GetDocumentsID{Context: ctx, Handler: handler}
}

/*
	GetDocumentsID swagger:route GET /documents/{id} getDocumentsId

Get document by ID
*/
type GetDocumentsID struct {
	Context *middleware.Context
	Handler GetDocumentsIDHandler
}

func (o *GetDocumentsID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetDocumentsIDParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
