// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/imsoul11/personalDocStore/models"
)

// GetDocumentsOKCode is the HTTP code returned for type GetDocumentsOK
const GetDocumentsOKCode int = 200

/*
GetDocumentsOK List of documents

swagger:response getDocumentsOK
*/
type GetDocumentsOK struct {

	/*
	  In: Body
	*/
	Payload *models.DocumentsListResponse `json:"body,omitempty"`
}

// NewGetDocumentsOK creates GetDocumentsOK with default headers values
func NewGetDocumentsOK() *GetDocumentsOK {

	return &GetDocumentsOK{}
}

// WithPayload adds the payload to the get documents o k response
func (o *GetDocumentsOK) WithPayload(payload *models.DocumentsListResponse) *GetDocumentsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get documents o k response
func (o *GetDocumentsOK) SetPayload(payload *models.DocumentsListResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDocumentsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetDocumentsUnauthorizedCode is the HTTP code returned for type GetDocumentsUnauthorized
const GetDocumentsUnauthorizedCode int = 401

/*
GetDocumentsUnauthorized Unauthorized

swagger:response getDocumentsUnauthorized
*/
type GetDocumentsUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewGetDocumentsUnauthorized creates GetDocumentsUnauthorized with default headers values
func NewGetDocumentsUnauthorized() *GetDocumentsUnauthorized {

	return &GetDocumentsUnauthorized{}
}

// WithPayload adds the payload to the get documents unauthorized response
func (o *GetDocumentsUnauthorized) WithPayload(payload *models.ErrorResponse) *GetDocumentsUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get documents unauthorized response
func (o *GetDocumentsUnauthorized) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDocumentsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetDocumentsInternalServerErrorCode is the HTTP code returned for type GetDocumentsInternalServerError
const GetDocumentsInternalServerErrorCode int = 500

/*
GetDocumentsInternalServerError Internal server error

swagger:response getDocumentsInternalServerError
*/
type GetDocumentsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewGetDocumentsInternalServerError creates GetDocumentsInternalServerError with default headers values
func NewGetDocumentsInternalServerError() *GetDocumentsInternalServerError {

	return &GetDocumentsInternalServerError{}
}

// WithPayload adds the payload to the get documents internal server error response
func (o *GetDocumentsInternalServerError) WithPayload(payload *models.ErrorResponse) *GetDocumentsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get documents internal server error response
func (o *GetDocumentsInternalServerError) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDocumentsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
