// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostUsersLoginHandlerFunc turns a function with the right signature into a post users login handler
type PostUsersLoginHandlerFunc func(PostUsersLoginParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostUsersLoginHandlerFunc) Handle(params PostUsersLoginParams) middleware.Responder {
	return fn(params)
}

// PostUsersLoginHandler interface for that can handle valid post users login params
type PostUsersLoginHandler interface {
	Handle(PostUsersLoginParams) middleware.Responder
}

// NewPostUsersLogin creates a new http.Handler for the post users login operation
func NewPostUsersLogin(ctx *middleware.Context, handler PostUsersLoginHandler) *PostUsersLogin {
	return &PostUsersLogin{Context: ctx, Handler: handler}
}

/*
	PostUsersLogin swagger:route POST /users/login postUsersLogin

Login
*/
type PostUsersLogin struct {
	Context *middleware.Context
	Handler PostUsersLoginHandler
}

func (o *PostUsersLogin) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostUsersLoginParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostUsersLoginBody post users login body
//
// swagger:model PostUsersLoginBody
type PostUsersLoginBody struct {

	// email
	// Required: true
	// Format: email
	Email *strfmt.Email `json:"email"`

	// password
	// Required: true
	Password *string `json:"password"`
}

// Validate validates this post users login body
func (o *PostUsersLoginBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validatePassword(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostUsersLoginBody) validateEmail(formats strfmt.Registry) error {

	if err := validate.Required("body"+"."+"email", "body", o.Email); err != nil {
		return err
	}

	if err := validate.FormatOf("body"+"."+"email", "body", "email", o.Email.String(), formats); err != nil {
		return err
	}

	return nil
}

func (o *PostUsersLoginBody) validatePassword(formats strfmt.Registry) error {

	if err := validate.Required("body"+"."+"password", "body", o.Password); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post users login body based on context it is used
func (o *PostUsersLoginBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostUsersLoginBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostUsersLoginBody) UnmarshalBinary(b []byte) error {
	var res PostUsersLoginBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
