// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostUsersProfileHandlerFunc turns a function with the right signature into a post users profile handler
type PostUsersProfileHandlerFunc func(PostUsersProfileParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostUsersProfileHandlerFunc) Handle(params PostUsersProfileParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostUsersProfileHandler interface for that can handle valid post users profile params
type PostUsersProfileHandler interface {
	Handle(PostUsersProfileParams, interface{}) middleware.Responder
}

// NewPostUsersProfile creates a new http.Handler for the post users profile operation
func NewPostUsersProfile(ctx *middleware.Context, handler PostUsersProfileHandler) *PostUsersProfile {
	return &PostUsersProfile{Context: ctx, Handler: handler}
}

/*
	PostUsersProfile swagger:route POST /users/profile postUsersProfile

Update user profile
*/
type PostUsersProfile struct {
	Context *middleware.Context
	Handler PostUsersProfileHandler
}

func (o *PostUsersProfile) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostUsersProfileParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostUsersProfileBody post users profile body
//
// swagger:model PostUsersProfileBody
type PostUsersProfileBody struct {

	// address
	Address string `json:"address,omitempty"`

	// dob
	// Format: date
	Dob strfmt.Date `json:"dob,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this post users profile body
func (o *PostUsersProfileBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateDob(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostUsersProfileBody) validateDob(formats strfmt.Registry) error {
	if swag.IsZero(o.Dob) { // not required
		return nil
	}

	if err := validate.FormatOf("body"+"."+"dob", "body", "date", o.Dob.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post users profile body based on context it is used
func (o *PostUsersProfileBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostUsersProfileBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostUsersProfileBody) UnmarshalBinary(b []byte) error {
	var res PostUsersProfileBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
