// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostDocumentsCreatedCode is the HTTP code returned for type PostDocumentsCreated
const PostDocumentsCreatedCode int = 201

/*
PostDocumentsCreated Created

swagger:response postDocumentsCreated
*/
type PostDocumentsCreated struct {
}

// NewPostDocumentsCreated creates PostDocumentsCreated with default headers values
func NewPostDocumentsCreated() *PostDocumentsCreated {

	return &PostDocumentsCreated{}
}

// WriteResponse to the client
func (o *PostDocumentsCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// PostDocumentsBadRequestCode is the HTTP code returned for type PostDocumentsBadRequest
const PostDocumentsBadRequestCode int = 400

/*
PostDocumentsBadRequest Bad request

swagger:response postDocumentsBadRequest
*/
type PostDocumentsBadRequest struct {
}

// NewPostDocumentsBadRequest creates PostDocumentsBadRequest with default headers values
func NewPostDocumentsBadRequest() *PostDocumentsBadRequest {

	return &PostDocumentsBadRequest{}
}

// WriteResponse to the client
func (o *PostDocumentsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PostDocumentsUnauthorizedCode is the HTTP code returned for type PostDocumentsUnauthorized
const PostDocumentsUnauthorizedCode int = 401

/*
PostDocumentsUnauthorized Unauthorized

swagger:response postDocumentsUnauthorized
*/
type PostDocumentsUnauthorized struct {
}

// NewPostDocumentsUnauthorized creates PostDocumentsUnauthorized with default headers values
func NewPostDocumentsUnauthorized() *PostDocumentsUnauthorized {

	return &PostDocumentsUnauthorized{}
}

// WriteResponse to the client
func (o *PostDocumentsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
