// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostDocumentsHandlerFunc turns a function with the right signature into a post documents handler
type PostDocumentsHandlerFunc func(PostDocumentsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostDocumentsHandlerFunc) Handle(params PostDocumentsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostDocumentsHandler interface for that can handle valid post documents params
type PostDocumentsHandler interface {
	Handle(PostDocumentsParams, interface{}) middleware.Responder
}

// NewPostDocuments creates a new http.Handler for the post documents operation
func NewPostDocuments(ctx *middleware.Context, handler PostDocumentsHandler) *PostDocuments {
	return &PostDocuments{Context: ctx, Handler: handler}
}

/*
	PostDocuments swagger:route POST /documents postDocuments

Upload document
*/
type PostDocuments struct {
	Context *middleware.Context
	Handler PostDocumentsHandler
}

func (o *PostDocuments) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostDocumentsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
