// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostUsersRegisterCreatedCode is the HTTP code returned for type PostUsersRegisterCreated
const PostUsersRegisterCreatedCode int = 201

/*
PostUsersRegisterCreated Created

swagger:response postUsersRegisterCreated
*/
type PostUsersRegisterCreated struct {
}

// NewPostUsersRegisterCreated creates PostUsersRegisterCreated with default headers values
func NewPostUsersRegisterCreated() *PostUsersRegisterCreated {

	return &PostUsersRegisterCreated{}
}

// WriteResponse to the client
func (o *PostUsersRegisterCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// PostUsersRegisterBadRequestCode is the HTTP code returned for type PostUsersRegisterBadRequest
const PostUsersRegisterBadRequestCode int = 400

/*
PostUsersRegisterBadRequest Bad request

swagger:response postUsersRegisterBadRequest
*/
type PostUsersRegisterBadRequest struct {
}

// NewPostUsersRegisterBadRequest creates PostUsersRegisterBadRequest with default headers values
func NewPostUsersRegisterBadRequest() *PostUsersRegisterBadRequest {

	return &PostUsersRegisterBadRequest{}
}

// WriteResponse to the client
func (o *PostUsersRegisterBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PostUsersRegisterConflictCode is the HTTP code returned for type PostUsersRegisterConflict
const PostUsersRegisterConflictCode int = 409

/*
PostUsersRegisterConflict Email already exists

swagger:response postUsersRegisterConflict
*/
type PostUsersRegisterConflict struct {
}

// NewPostUsersRegisterConflict creates PostUsersRegisterConflict with default headers values
func NewPostUsersRegisterConflict() *PostUsersRegisterConflict {

	return &PostUsersRegisterConflict{}
}

// WriteResponse to the client
func (o *PostUsersRegisterConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(409)
}
