// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/imsoul11/personalDocStore/models"
)

// PostUsersRegisterCreatedCode is the HTTP code returned for type PostUsersRegisterCreated
const PostUsersRegisterCreatedCode int = 201

/*
PostUsersRegisterCreated Created

swagger:response postUsersRegisterCreated
*/
type PostUsersRegisterCreated struct {

	/*
	  In: Body
	*/
	Payload *models.AckResponse `json:"body,omitempty"`
}

// NewPostUsersRegisterCreated creates PostUsersRegisterCreated with default headers values
func NewPostUsersRegisterCreated() *PostUsersRegisterCreated {

	return &PostUsersRegisterCreated{}
}

// WithPayload adds the payload to the post users register created response
func (o *PostUsersRegisterCreated) WithPayload(payload *models.AckResponse) *PostUsersRegisterCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post users register created response
func (o *PostUsersRegisterCreated) SetPayload(payload *models.AckResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUsersRegisterCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostUsersRegisterBadRequestCode is the HTTP code returned for type PostUsersRegisterBadRequest
const PostUsersRegisterBadRequestCode int = 400

/*
PostUsersRegisterBadRequest Bad request

swagger:response postUsersRegisterBadRequest
*/
type PostUsersRegisterBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewPostUsersRegisterBadRequest creates PostUsersRegisterBadRequest with default headers values
func NewPostUsersRegisterBadRequest() *PostUsersRegisterBadRequest {

	return &PostUsersRegisterBadRequest{}
}

// WithPayload adds the payload to the post users register bad request response
func (o *PostUsersRegisterBadRequest) WithPayload(payload *models.ErrorResponse) *PostUsersRegisterBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post users register bad request response
func (o *PostUsersRegisterBadRequest) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUsersRegisterBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostUsersRegisterConflictCode is the HTTP code returned for type PostUsersRegisterConflict
const PostUsersRegisterConflictCode int = 409

/*
PostUsersRegisterConflict Email already exists

swagger:response postUsersRegisterConflict
*/
type PostUsersRegisterConflict struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewPostUsersRegisterConflict creates PostUsersRegisterConflict with default headers values
func NewPostUsersRegisterConflict() *PostUsersRegisterConflict {

	return &PostUsersRegisterConflict{}
}

// WithPayload adds the payload to the post users register conflict response
func (o *PostUsersRegisterConflict) WithPayload(payload *models.ErrorResponse) *PostUsersRegisterConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post users register conflict response
func (o *PostUsersRegisterConflict) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUsersRegisterConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
