// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/imsoul11/personalDocStore/models"
)

// PostUsersProfileOKCode is the HTTP code returned for type PostUsersProfileOK
const PostUsersProfileOKCode int = 200

/*
PostUsersProfileOK OK

swagger:response postUsersProfileOK
*/
type PostUsersProfileOK struct {

	/*
	  In: Body
	*/
	Payload *models.AckResponse `json:"body,omitempty"`
}

// NewPostUsersProfileOK creates PostUsersProfileOK with default headers values
func NewPostUsersProfileOK() *PostUsersProfileOK {

	return &PostUsersProfileOK{}
}

// WithPayload adds the payload to the post users profile o k response
func (o *PostUsersProfileOK) WithPayload(payload *models.AckResponse) *PostUsersProfileOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post users profile o k response
func (o *PostUsersProfileOK) SetPayload(payload *models.AckResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUsersProfileOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostUsersProfileBadRequestCode is the HTTP code returned for type PostUsersProfileBadRequest
const PostUsersProfileBadRequestCode int = 400

/*
PostUsersProfileBadRequest Bad request

swagger:response postUsersProfileBadRequest
*/
type PostUsersProfileBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewPostUsersProfileBadRequest creates PostUsersProfileBadRequest with default headers values
func NewPostUsersProfileBadRequest() *PostUsersProfileBadRequest {

	return &PostUsersProfileBadRequest{}
}

// WithPayload adds the payload to the post users profile bad request response
func (o *PostUsersProfileBadRequest) WithPayload(payload *models.ErrorResponse) *PostUsersProfileBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post users profile bad request response
func (o *PostUsersProfileBadRequest) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUsersProfileBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostUsersProfileUnauthorizedCode is the HTTP code returned for type PostUsersProfileUnauthorized
const PostUsersProfileUnauthorizedCode int = 401

/*
PostUsersProfileUnauthorized Unauthorized

swagger:response postUsersProfileUnauthorized
*/
type PostUsersProfileUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewPostUsersProfileUnauthorized creates PostUsersProfileUnauthorized with default headers values
func NewPostUsersProfileUnauthorized() *PostUsersProfileUnauthorized {

	return &PostUsersProfileUnauthorized{}
}

// WithPayload adds the payload to the post users profile unauthorized response
func (o *PostUsersProfileUnauthorized) WithPayload(payload *models.ErrorResponse) *PostUsersProfileUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post users profile unauthorized response
func (o *PostUsersProfileUnauthorized) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUsersProfileUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
