// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostUsersProfileOKCode is the HTTP code returned for type PostUsersProfileOK
const PostUsersProfileOKCode int = 200

/*
PostUsersProfileOK OK

swagger:response postUsersProfileOK
*/
type PostUsersProfileOK struct {
}

// NewPostUsersProfileOK creates PostUsersProfileOK with default headers values
func NewPostUsersProfileOK() *PostUsersProfileOK {

	return &PostUsersProfileOK{}
}

// WriteResponse to the client
func (o *PostUsersProfileOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostUsersProfileBadRequestCode is the HTTP code returned for type PostUsersProfileBadRequest
const PostUsersProfileBadRequestCode int = 400

/*
PostUsersProfileBadRequest Bad request

swagger:response postUsersProfileBadRequest
*/
type PostUsersProfileBadRequest struct {
}

// NewPostUsersProfileBadRequest creates PostUsersProfileBadRequest with default headers values
func NewPostUsersProfileBadRequest() *PostUsersProfileBadRequest {

	return &PostUsersProfileBadRequest{}
}

// WriteResponse to the client
func (o *PostUsersProfileBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PostUsersProfileUnauthorizedCode is the HTTP code returned for type PostUsersProfileUnauthorized
const PostUsersProfileUnauthorizedCode int = 401

/*
PostUsersProfileUnauthorized Unauthorized

swagger:response postUsersProfileUnauthorized
*/
type PostUsersProfileUnauthorized struct {
}

// NewPostUsersProfileUnauthorized creates PostUsersProfileUnauthorized with default headers values
func NewPostUsersProfileUnauthorized() *PostUsersProfileUnauthorized {

	return &PostUsersProfileUnauthorized{}
}

// WriteResponse to the client
func (o *PostUsersProfileUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
