// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostUsersRegisterHandlerFunc turns a function with the right signature into a post users register handler
type PostUsersRegisterHandlerFunc func(PostUsersRegisterParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostUsersRegisterHandlerFunc) Handle(params PostUsersRegisterParams) middleware.Responder {
	return fn(params)
}

// PostUsersRegisterHandler interface for that can handle valid post users register params
type PostUsersRegisterHandler interface {
	Handle(PostUsersRegisterParams) middleware.Responder
}

// NewPostUsersRegister creates a new http.Handler for the post users register operation
func NewPostUsersRegister(ctx *middleware.Context, handler PostUsersRegisterHandler) *PostUsersRegister {
	return &PostUsersRegister{Context: ctx, Handler: handler}
}

/*
	PostUsersRegister swagger:route POST /users/register postUsersRegister

Register a new user
*/
type PostUsersRegister struct {
	Context *middleware.Context
	Handler PostUsersRegisterHandler
}

func (o *PostUsersRegister) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostUsersRegisterParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostUsersRegisterBody post users register body
//
// swagger:model PostUsersRegisterBody
type PostUsersRegisterBody struct {

	// email
	// Required: true
	// Format: email
	Email *strfmt.Email `json:"email"`

	// password
	// Required: true
	Password *string `json:"password"`
}

// Validate validates this post users register body
func (o *PostUsersRegisterBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validatePassword(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostUsersRegisterBody) validateEmail(formats strfmt.Registry) error {

	if err := validate.Required("body"+"."+"email", "body", o.Email); err != nil {
		return err
	}

	if err := validate.FormatOf("body"+"."+"email", "body", "email", o.Email.String(), formats); err != nil {
		return err
	}

	return nil
}

func (o *PostUsersRegisterBody) validatePassword(formats strfmt.Registry) error {

	if err := validate.Required("body"+"."+"password", "body", o.Password); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post users register body based on context it is used
func (o *PostUsersRegisterBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostUsersRegisterBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostUsersRegisterBody) UnmarshalBinary(b []byte) error {
	var res PostUsersRegisterBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
