// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostUsersLoginOKCode is the HTTP code returned for type PostUsersLoginOK
const PostUsersLoginOKCode int = 200

/*
PostUsersLoginOK OK

swagger:response postUsersLoginOK
*/
type PostUsersLoginOK struct {
}

// NewPostUsersLoginOK creates PostUsersLoginOK with default headers values
func NewPostUsersLoginOK() *PostUsersLoginOK {

	return &PostUsersLoginOK{}
}

// WriteResponse to the client
func (o *PostUsersLoginOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostUsersLoginBadRequestCode is the HTTP code returned for type PostUsersLoginBadRequest
const PostUsersLoginBadRequestCode int = 400

/*
PostUsersLoginBadRequest Bad request

swagger:response postUsersLoginBadRequest
*/
type PostUsersLoginBadRequest struct {
}

// NewPostUsersLoginBadRequest creates PostUsersLoginBadRequest with default headers values
func NewPostUsersLoginBadRequest() *PostUsersLoginBadRequest {

	return &PostUsersLoginBadRequest{}
}

// WriteResponse to the client
func (o *PostUsersLoginBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PostUsersLoginUnauthorizedCode is the HTTP code returned for type PostUsersLoginUnauthorized
const PostUsersLoginUnauthorizedCode int = 401

/*
PostUsersLoginUnauthorized Invalid credentials

swagger:response postUsersLoginUnauthorized
*/
type PostUsersLoginUnauthorized struct {
}

// NewPostUsersLoginUnauthorized creates PostUsersLoginUnauthorized with default headers values
func NewPostUsersLoginUnauthorized() *PostUsersLoginUnauthorized {

	return &PostUsersLoginUnauthorized{}
}

// WriteResponse to the client
func (o *PostUsersLoginUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
