// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "docstore API",
    "version": "1.0"
  },
  "basePath": "/",
  "paths": {
    "/documents": {
      "get": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "summary": "List documents for the current user",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "default": 50,
            "x-example": 20,
            "description": "Maximum number of documents to return for this page",
            "name": "limit",
            "in": "query",
            "minimum": 1
          },
          {
            "type": "integer",
            "format": "int64",
            "default": 0,
            "x-example": 40,
            "description": "Number of documents to skip before starting this page",
            "name": "offset",
            "in": "query",
            "minimum": 0
          },
          {
            "type": "string",
            "enum": [
              "uploaded",
              "processing",
              "completed",
              "failed"
            ],
            "x-example": "completed",
            "description": "Optional document status filter",
            "name": "status",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "List of documents",
            "schema": {
              "$ref": "#/definitions/DocumentsListResponse"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "consumes": [
          "multipart/form-data"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Upload document",
        "parameters": [
          {
            "type": "file",
            "description": "The document file to upload",
            "name": "file",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "description": "Optional filename override",
            "name": "filename",
            "in": "formData"
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/DocumentCreatedResponse"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/documents/{id}": {
      "get": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Get document by ID",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "Document ID",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Document details",
            "schema": {
              "$ref": "#/definitions/DocumentResponse"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "404": {
            "description": "Not found",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/users/login": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Login",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "email",
                "password"
              ],
              "properties": {
                "email": {
                  "type": "string",
                  "format": "email"
                },
                "password": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/LoginResponse"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "401": {
            "description": "Invalid credentials",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/users/profile": {
      "get": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Get current user profile",
        "responses": {
          "200": {
            "description": "Profile details",
            "schema": {
              "$ref": "#/definitions/UserProfileResponse"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Update user profile",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "address": {
                  "type": "string"
                },
                "dob": {
                  "type": "string",
                  "format": "date"
                },
                "name": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/AckResponse"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/users/register": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Register a new user",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "email",
                "password"
              ],
              "properties": {
                "email": {
                  "type": "string",
                  "format": "email"
                },
                "password": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/AckResponse"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "409": {
            "description": "Email already exists",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "AckResponse": {
      "type": "object",
      "required": [
        "success",
        "acknowledgement"
      ],
      "properties": {
        "acknowledgement": {
          "type": "string",
          "example": "Request processed successfully"
        },
        "success": {
          "type": "boolean",
          "example": true
        }
      }
    },
    "Document": {
      "type": "object",
      "required": [
        "id",
        "user_id",
        "filename",
        "status",
        "created_at",
        "updated_at"
      ],
      "properties": {
        "created_at": {
          "type": "string",
          "format": "date-time"
        },
        "filename": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "status": {
          "type": "string",
          "example": "uploaded",
          "enum": [
            "uploaded",
            "processing",
            "completed",
            "failed"
          ]
        },
        "updated_at": {
          "type": "string",
          "format": "date-time",
          "example": "2026-01-02T05:04:05Z"
        },
        "user_id": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "DocumentCreatedResponse": {
      "type": "object",
      "required": [
        "success",
        "acknowledgement",
        "document"
      ],
      "properties": {
        "acknowledgement": {
          "type": "string",
          "example": "Document uploaded and queued for processing"
        },
        "document": {
          "$ref": "#/definitions/Document"
        },
        "success": {
          "type": "boolean",
          "example": true
        }
      }
    },
    "DocumentResponse": {
      "type": "object",
      "required": [
        "success",
        "acknowledgement",
        "document"
      ],
      "properties": {
        "acknowledgement": {
          "type": "string",
          "example": "Document fetched successfully"
        },
        "document": {
          "$ref": "#/definitions/Document"
        },
        "success": {
          "type": "boolean",
          "example": true
        }
      }
    },
    "DocumentsListResponse": {
      "type": "object",
      "required": [
        "success",
        "acknowledgement",
        "documents",
        "total_count"
      ],
      "properties": {
        "acknowledgement": {
          "type": "string",
          "example": "Documents fetched successfully"
        },
        "documents": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Document"
          }
        },
        "success": {
          "type": "boolean",
          "example": true
        },
        "total_count": {
          "type": "integer",
          "format": "int64",
          "example": 42
        }
      }
    },
    "ErrorResponse": {
      "type": "object",
      "required": [
        "success",
        "acknowledgement",
        "code",
        "message"
      ],
      "properties": {
        "acknowledgement": {
          "type": "string",
          "example": "Request failed"
        },
        "code": {
          "type": "integer",
          "format": "int32",
          "example": 400
        },
        "message": {
          "type": "string",
          "example": "Invalid request payload"
        },
        "success": {
          "type": "boolean",
          "example": false
        }
      }
    },
    "LoginResponse": {
      "type": "object",
      "required": [
        "success",
        "acknowledgement",
        "token"
      ],
      "properties": {
        "acknowledgement": {
          "type": "string",
          "example": "Login successful"
        },
        "success": {
          "type": "boolean",
          "example": true
        },
        "token": {
          "type": "string"
        }
      }
    },
    "UserProfile": {
      "type": "object",
      "required": [
        "id",
        "email",
        "created_at"
      ],
      "properties": {
        "address": {
          "type": "string"
        },
        "created_at": {
          "type": "string",
          "format": "date-time"
        },
        "dob": {
          "type": "string"
        },
        "email": {
          "type": "string",
          "format": "email"
        },
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "UserProfileResponse": {
      "type": "object",
      "required": [
        "success",
        "acknowledgement",
        "user"
      ],
      "properties": {
        "acknowledgement": {
          "type": "string",
          "example": "Profile fetched successfully"
        },
        "success": {
          "type": "boolean",
          "example": true
        },
        "user": {
          "$ref": "#/definitions/UserProfile"
        }
      }
    }
  },
  "securityDefinitions": {
    "Bearer": {
      "description": "Bearer token (e.g. \"Bearer \u0026lt;token\u0026gt;\")",
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "docstore API",
    "version": "1.0"
  },
  "basePath": "/",
  "paths": {
    "/documents": {
      "get": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "summary": "List documents for the current user",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "default": 50,
            "x-example": 20,
            "description": "Maximum number of documents to return for this page",
            "name": "limit",
            "in": "query",
            "minimum": 1
          },
          {
            "type": "integer",
            "format": "int64",
            "default": 0,
            "x-example": 40,
            "description": "Number of documents to skip before starting this page",
            "name": "offset",
            "in": "query",
            "minimum": 0
          },
          {
            "type": "string",
            "enum": [
              "uploaded",
              "processing",
              "completed",
              "failed"
            ],
            "x-example": "completed",
            "description": "Optional document status filter",
            "name": "status",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "List of documents",
            "schema": {
              "$ref": "#/definitions/DocumentsListResponse"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "consumes": [
          "multipart/form-data"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Upload document",
        "parameters": [
          {
            "type": "file",
            "description": "The document file to upload",
            "name": "file",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "description": "Optional filename override",
            "name": "filename",
            "in": "formData"
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/DocumentCreatedResponse"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/documents/{id}": {
      "get": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Get document by ID",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "Document ID",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Document details",
            "schema": {
              "$ref": "#/definitions/DocumentResponse"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "404": {
            "description": "Not found",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/users/login": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Login",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "email",
                "password"
              ],
              "properties": {
                "email": {
                  "type": "string",
                  "format": "email"
                },
                "password": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/LoginResponse"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "401": {
            "description": "Invalid credentials",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/users/profile": {
      "get": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Get current user profile",
        "responses": {
          "200": {
            "description": "Profile details",
            "schema": {
              "$ref": "#/definitions/UserProfileResponse"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Update user profile",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "address": {
                  "type": "string"
                },
                "dob": {
                  "type": "string",
                  "format": "date"
                },
                "name": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/AckResponse"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/users/register": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Register a new user",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "required": [
                "email",
                "password"
              ],
              "properties": {
                "email": {
                  "type": "string",
                  "format": "email"
                },
                "password": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/AckResponse"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "409": {
            "description": "Email already exists",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "AckResponse": {
      "type": "object",
      "required": [
        "success",
        "acknowledgement"
      ],
      "properties": {
        "acknowledgement": {
          "type": "string",
          "example": "Request processed successfully"
        },
        "success": {
          "type": "boolean",
          "example": true
        }
      }
    },
    "Document": {
      "type": "object",
      "required": [
        "id",
        "user_id",
        "filename",
        "status",
        "created_at",
        "updated_at"
      ],
      "properties": {
        "created_at": {
          "type": "string",
          "format": "date-time"
        },
        "filename": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "status": {
          "type": "string",
          "example": "uploaded",
          "enum": [
            "uploaded",
            "processing",
            "completed",
            "failed"
          ]
        },
        "updated_at": {
          "type": "string",
          "format": "date-time",
          "example": "2026-01-02T05:04:05Z"
        },
        "user_id": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "DocumentCreatedResponse": {
      "type": "object",
      "required": [
        "success",
        "acknowledgement",
        "document"
      ],
      "properties": {
        "acknowledgement": {
          "type": "string",
          "example": "Document uploaded and queued for processing"
        },
        "document": {
          "$ref": "#/definitions/Document"
        },
        "success": {
          "type": "boolean",
          "example": true
        }
      }
    },
    "DocumentResponse": {
      "type": "object",
      "required": [
        "success",
        "acknowledgement",
        "document"
      ],
      "properties": {
        "acknowledgement": {
          "type": "string",
          "example": "Document fetched successfully"
        },
        "document": {
          "$ref": "#/definitions/Document"
        },
        "success": {
          "type": "boolean",
          "example": true
        }
      }
    },
    "DocumentsListResponse": {
      "type": "object",
      "required": [
        "success",
        "acknowledgement",
        "documents",
        "total_count"
      ],
      "properties": {
        "acknowledgement": {
          "type": "string",
          "example": "Documents fetched successfully"
        },
        "documents": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Document"
          }
        },
        "success": {
          "type": "boolean",
          "example": true
        },
        "total_count": {
          "type": "integer",
          "format": "int64",
          "example": 42
        }
      }
    },
    "ErrorResponse": {
      "type": "object",
      "required": [
        "success",
        "acknowledgement",
        "code",
        "message"
      ],
      "properties": {
        "acknowledgement": {
          "type": "string",
          "example": "Request failed"
        },
        "code": {
          "type": "integer",
          "format": "int32",
          "example": 400
        },
        "message": {
          "type": "string",
          "example": "Invalid request payload"
        },
        "success": {
          "type": "boolean",
          "example": false
        }
      }
    },
    "LoginResponse": {
      "type": "object",
      "required": [
        "success",
        "acknowledgement",
        "token"
      ],
      "properties": {
        "acknowledgement": {
          "type": "string",
          "example": "Login successful"
        },
        "success": {
          "type": "boolean",
          "example": true
        },
        "token": {
          "type": "string"
        }
      }
    },
    "UserProfile": {
      "type": "object",
      "required": [
        "id",
        "email",
        "created_at"
      ],
      "properties": {
        "address": {
          "type": "string"
        },
        "created_at": {
          "type": "string",
          "format": "date-time"
        },
        "dob": {
          "type": "string"
        },
        "email": {
          "type": "string",
          "format": "email"
        },
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "UserProfileResponse": {
      "type": "object",
      "required": [
        "success",
        "acknowledgement",
        "user"
      ],
      "properties": {
        "acknowledgement": {
          "type": "string",
          "example": "Profile fetched successfully"
        },
        "success": {
          "type": "boolean",
          "example": true
        },
        "user": {
          "$ref": "#/definitions/UserProfile"
        }
      }
    }
  },
  "securityDefinitions": {
    "Bearer": {
      "description": "Bearer token (e.g. \"Bearer \u0026lt;token\u0026gt;\")",
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  }
}`))
}
