// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AckResponse ack response
//
// swagger:model AckResponse
type AckResponse struct {

	// acknowledgement
	// Example: Request processed successfully
	// Required: true
	Acknowledgement *string `json:"acknowledgement"`

	// success
	// Example: true
	// Required: true
	Success *bool `json:"success"`
}

// Validate validates this ack response
func (m *AckResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAcknowledgement(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSuccess(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AckResponse) validateAcknowledgement(formats strfmt.Registry) error {

	if err := validate.Required("acknowledgement", "body", m.Acknowledgement); err != nil {
		return err
	}

	return nil
}

func (m *AckResponse) validateSuccess(formats strfmt.Registry) error {

	if err := validate.Required("success", "body", m.Success); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this ack response based on context it is used
func (m *AckResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AckResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AckResponse) UnmarshalBinary(b []byte) error {
	var res AckResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
